version: "3.8"

services:
  frontend-app:
    image: example-frontend
    build:
      context: ./example-frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  backend-server:
    image: example-backend
    build:
      context: ./example-backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:3000
      - REDIS_HOST=redis_service
      - POSTGRES_HOST=postgres_service
    depends_on:
      - redis_service
      - postgres_service

  redis_service:
    image: redis
    restart: unless-stopped
    volumes:
      - ./example-backend/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  postgres_service:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_HOST: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    # volumes:
    # - database:/var/lib/postgresql/data
# volumes:
# database:
