version: "3.8"

services:
  frontend-app:
    image: example-frontend-slim
    build:
      context: ./example-frontend/
      dockerfile: slim.Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  backend-server:
    image: example-backend-slim
    build:
      context: ./example-backend/
      dockerfile: slim.Dockerfile
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:3000
