name: Release Node.js app

on:
  push:
    branches:
      - main
    # Added specifically to avoid creating other repo and running actions from this directory only for express-app
    paths:
      - "part3/express-app/**"
      - ".github/workflows/part3-express-app,yml"

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mmiglioranza22/express-app:latest
